DEBUG = True
DEBUG_MQTT = True
IP = "192.168.0.114"
SQLALCHEMY_DATABASE_URI = 'sqlite:///C:/CloudServer/database.db'
SQLALCHEMY_TRACK_MODIFICATIONS = False
SECRET_KEY = 'scc331sharedsecretkey'
DATABASE_NAME = 'database.db'

ADMIN_CHANNELS = []
ADMIN_ASSIGNED_CHANNELS = {}

FCM = "AAAAmg2JIFk:APA91bFAeucUqBmbLwCQYdb91mOmuFgYXYa8fa_hGpODnM7r5cugEMdlllk0p4MOglh7gGc0LHL0xqFprfAHBRnbKW7zo0Vo5GkyeauPpopskjfRw_3co8K96NTYrptWrLwW76w60Uk9"
